config/routes.rb
Rails.application.routes.draw do
  resources :songs
  resources :artists
  get 'hip/hop'
  get 'top_artists' => 'hip#top_artists'
  root 'hip#hop'

end

app/models/artist.rb
class Artist < ActiveRecord::Base
  has_many :songs
  validates :name, presence:true
  validates :name, uniqueness:true

  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
end

app/models/song.rb
class Song < ActiveRecord::Base
  belongs_to :artist
  validates :name, presence: true
  validates :artist_id, presence: true
  validates :rating, presence: true
  validates :name, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, only: [:show, :edit, :update, :destroy]

  # GET /artists
  # GET /artists.json
  def index
    @artists = Artist.all
  end

  # GET /artists/1
  # GET /artists/1.json
  def show
  end

  # GET /artists/new
  def new
    @artist = Artist.new
  end

  # GET /artists/1/edit
  def edit
  end

  # POST /artists
  # POST /artists.json
  def create
    @artist = Artist.new(artist_params)

    respond_to do |format|
      if @artist.save
        format.html { redirect_to @artist, notice: 'Artist was successfully created.' }
        format.json { render :show, status: :created, location: @artist }
      else
        format.html { render :new }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /artists/1
  # PATCH/PUT /artists/1.json
  def update
    respond_to do |format|
      if @artist.update(artist_params)
        format.html { redirect_to @artist, notice: 'Artist was successfully updated.' }
        format.json { render :show, status: :ok, location: @artist }
      else
        format.html { render :edit }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /artists/1
  # DELETE /artists/1.json
  def destroy
    @artist.destroy
    @artist.songs.each do |song|
      song.destroy
    end
    respond_to do |format|
      format.html { redirect_to artists_url, notice: 'Artist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_artist
      @artist = Artist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def artist_params
      params.require(:artist).permit(:name, :avatar, :rating)
    end
end

app/controllers/hip_controller.rb
class HipController < ApplicationController
  def hop
    @songs = Song.order(rating: :desc).limit(5)
  end
  def top_artists
    @artists = Artist.order(rating: :desc).limit(5)
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: [:show, :edit, :update, :destroy]

  # GET /songs
  # GET /songs.json
  def index
    @songs = Song.all
  end

  # GET /songs/1
  # GET /songs/1.json
  def show
  end

  # GET /songs/new
  def new
    @song = Song.new
    @artists = Artist.all
  end

  # GET /songs/1/edit
  def edit
    @artists = Artist.all
  end

  # POST /songs
  # POST /songs.json
  def create
    @song = Song.new(song_params)
    @artists = Artist.all
    respond_to do |format|
      if @song.save
        format.html { redirect_to @song, notice: 'Song was successfully created.' }
        format.json { render :show, status: :created, location: @song }
      else
        format.html { render :new }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /songs/1
  # PATCH/PUT /songs/1.json
  def update
    respond_to do |format|
      if @song.update(song_params)
        format.html { redirect_to @song, notice: 'Song was successfully updated.' }
        format.json { render :show, status: :ok, location: @song }
      else
        format.html { render :edit }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /songs/1
  # DELETE /songs/1.json
  def destroy
    @song.destroy
    respond_to do |format|
      format.html { redirect_to songs_url, notice: 'Song was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_song
      @song = Song.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def song_params
      params.require(:song).permit(:name, :rating, :artist_id, :url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/hip_helper.rb
module HipHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/artists/_form.html.erb
<div class="row">
  <div class="col-sm-6 col-sm-offset-3">
    <%= form_for(@artist) do |f| %>
      <% if @artist.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@artist.errors.count, "error") %> prohibited this artist from being saved:</h2>

          <ul>
          <% @artist.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field form-group">
        <%= f.label :name, class: "sr-only" %><br>
        <%= f.text_field :name, class: "form-control", placeholder: "Name" %>
      </div>
      <div class="field form-group">
        <%= f.select(:rating, ['1', '2', '3', '4', '5'], {include_blank: 'Rating'}, class: "form-control") %>
      </div>
      <div class="field form-group">
        <%= f.file_field :avatar %>
      </div>
      <div class="actions form-group">
        <%= f.submit class: "btn btn-primary btn-lg" %>
      </div>
    <% end %>
  </div>
</div>

app/views/artists/edit.html.erb
<h1>Editing Artist</h1>

<%= render 'form' %>

<%= link_to 'Show', @artist %> |
<%= link_to 'Back', artists_path %>

app/views/artists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>My Artists</h1>
<p>
  <%= link_to new_artist_path do %>
    <span class="glyphicon glyphicon-plus"></span> Add Artist
    <% end %>
</p>
<div class="row">
  <% @artists.each do |artist| %>
    <div class="col-md-6">
      <div class="well well-lg media">
        <div class="media-left media-middle">
          <% if artist.avatar_file_name %>
            <%= image_tag artist.avatar.url(:thumb), class: "media-object img-circle" %>
          <% end %>
        </div>
        <div class="media-body">
          <h1>
            <%= link_to artist.name, artist %>
          </h1>
          <h4><% artist.rating.times do %>
              <span class="glyphicon glyphicon-star"></span>
              <% end %>
          </h4>
          <p>
            <%= link_to edit_artist_path(artist) do %>
            <span class="glyphicon glyphicon-edit"></span>
            <% end %>
            <%= link_to artist, method: :delete, data: { confirm: 'Are you sure?' } do %>
            <span class="glyphicon glyphicon-trash"></span>
            <% end %>
          </p>
        </div>

      </div>

    </div>
  <% end %>
</div>

app/views/artists/new.html.erb
<h1>New Artist</h1>

<%= render 'form' %>

<%= link_to 'Back', artists_path %>

app/views/artists/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <%= link_to new_artist_path do %>
    <span class="glyphicon glyphicon-plus"></span> Add Artist
    <% end %>
</p>
<div class="row">
  <div class="col-md-12">
    <div class="well well-lg">
      <% if @artist.avatar_file_name %>
        <%= image_tag @artist.avatar.url(:medium), class: "img-responsive center-block img-circle" %>
      <% end %>
      <h2><%= @artist.name %></h2>
      <h4><% @artist.rating.times do %>
          <span class="glyphicon glyphicon-star"></span>
          <% end %>
      </h4>
      <% @artist.songs.each do |song| %>
      <p>
        <%= link_to song.name, song %>
      </p>
      <% end %>
    </div>
  </div>
</div>

<%= link_to 'Edit', edit_artist_path(@artist) %> |
<%= link_to 'Back', artists_path %>

app/views/hip/hop.html.erb
<div class="row">
  <h2>My Top 5 Songs</h2>
  <% @songs.each do |song| %>
  <div class="well well-lg">
    <h2>
      <%= link_to song.name, song %>
    </h2>
    <h3>
      by <%= link_to song.artist.name, song.artist %>
    </h3>
    <p>
      <% song.rating.times do %>
      <span class="glyphicon glyphicon-star"></span>
      <% end %>
    </p>

  </div>
<% end %>
</div>

app/views/hip/top_artists.html.erb
<div class="row">
  <h2>My Top 5 Artists</h2>
  <% @artists.each do |artist| %>
  <div class="col-md-6">
    <div class="well well-lg media">
      <div class="media-left media-middle">
      <% if artist.avatar_file_name %>
        <%= image_tag artist.avatar.url(:thumb), class: "media-object img-circle" %>
      <% end %>
      </div>
      <div class="media-body">
        <h1>
          <%= link_to artist.name, artist %>
        </h1>
        <h4><% artist.rating.times do %>
            <span class="glyphicon glyphicon-star"></span>
            <% end %>
        </h4>
      </div>
    </div>
  </div>

<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Top 5 Music</title>
  <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="site-wrapper">
    <div class="site-wrapper-inner">
      <div class="cover-container">
        <div class="masthead clearfix">
          <div class="inner">
            <h3 class="masthead-brand"><div class="glyphicon glyphicon-headphones"></div> Jeffrey's Top Music</h3>
            <nav>
              <ul class="nav masthead-nav">
                <li><%= link_to "Top 5 Songs", root_path %></li>
                <li><%= link_to "Top 5 Artists", top_artists_path %></li>
            	  <li><%= link_to "Artists", artists_path %></li>
            	  <li><%= link_to "Songs", songs_path %></li>
              </ul>
            </nav>
          </div>
        </div>
        <div class="inner cover">
          <%= yield %>
        </div>
        <div class="mastfoot">
          <div class="inner">
            <p>Jeffrey's Top 5 Music - 2015</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</body>
</html>

app/views/songs/_form.html.erb
<div class="row">
  <div class="col-sm-6 col-sm-offset-3">
    <%= form_for(@song) do |f| %>
      <% if @song.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@song.errors.count, "error") %> prohibited this song from being saved:</h2>

          <ul>
          <% @song.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field form-group">
        <%= f.label :name, class: "sr-only" %><br>
        <%= f.text_field :name, class: "form-control", placeholder: "Name" %>
      </div>
      <div class="field form-group">
        <%= f.label :url, class: "sr-only" %><br>
        <%= f.text_field :url, class: "form-control", placeholder: "Video URL" %>
      </div>
      <div class="field form-group">
        <%= f.select(:artist_id, @artists.collect {|a| [a.name, a.id]}, {include_blank: 'Please select an artist'}, class: "form-control") %>
      </div>
      <div class="field form-group">
        <%= f.select(:rating, ['1', '2', '3', '4', '5'], {include_blank: 'Rating'}, class: "form-control") %>
      </div>
      <div class="actions from-group">
        <%= f.submit class: "btn btn-primary btn-lg" %>
      </div>
    <% end %>
  </div>
</div>

app/views/songs/edit.html.erb
<h1>Editing Song</h1>

<%= render 'form' %>

<%= link_to 'Show', @song %> |
<%= link_to 'Back', songs_path %>

app/views/songs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>My Songs</h1>
<p>
  <%= link_to new_song_path do %>
    <span class="glyphicon glyphicon-plus"></span> Add Song
    <% end %>
</p>
<div class="row">
  <% @songs.each do |song| %>
  <div class="col-md-6">
    <div class="well">
      <h2><%= link_to song.name, song %><h2>
      <h3>by <%= link_to song.artist.name, song.artist %></h3>
      <h4><% song.rating.times do %>
          <span class="glyphicon glyphicon-star"></span>
          <% end %>
      </h4>
      <hr/>
      <p>
        <%= link_to edit_song_path(song) do %>
        <span class="glyphicon glyphicon-edit"></span>
        <% end %>
        <%= link_to song, method: :delete, data: { confirm: 'Are you sure?' } do %>
        <span class="glyphicon glyphicon-trash"></span>
        <% end %>
      </p>

    </div>
  </div>
  <% end %>
</div>

app/views/songs/new.html.erb
<h1>New Song</h1>

<%= render 'form' %>

<%= link_to 'Back', songs_path %>

app/views/songs/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <%= link_to new_song_path do %>
    <span class="glyphicon glyphicon-plus"></span> Add Song
    <% end %>
</p>
<div class="row">
  <div class="col-md-12">
    <div class="well well-lg">
      <h2><%= @song.name %></h2>
      <h3>by
      <%= link_to @song.artist.name, @song.artist %>
      </h3>
      <h4><% @song.rating.times do %>
          <span class="glyphicon glyphicon-star"></span>
          <% end %>
      </h4>
      <% if @song.url != "" %>
          <!-- Button trigger modal -->
      <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
        View Music Video
      </button>


      <!-- Modal -->
      <div class="modal fade bs-example-modal-lg" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog modal-lg" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              <h4 class="modal-title" id="myModalLabel"><%= @song.name %> by <%= @song.artist.name %></h4>
            </div>
            <div class="modal-body">
              <div class="embed-responsive embed-responsive-16by9">
                <iframe class="embed-responsive-item" src= <%= @song.url %> allowfullscreen> </iframe>
              </div>
            </div>
          </div>
        </div>
      </div>
      <% end %>

    </div>

  </div>
</div>
<%= link_to 'Edit', edit_song_path(@song) %> |
<%= link_to 'Back', songs_path %>